version: '3'

services:
    spacebox_api:
        build: .
        restart: always
        container_name: spacebox_api
        ports:
            - "5002:5002"
        volumes:
            - ./config:/config